# Generated by Django 6.0.5 on 2026-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
