# Generated by Django 6.0.5 on 2026-06-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0002_remove_teacher_password_teacher_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='school_teachers',
        ),
    ]
