# Generated by Django 6.0.5 on 2026-05-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0002_alter_schoolclass_homeroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_base.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
