# Generated by Django 6.0.5 on 2026-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0003_alter_teacher_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123456', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
