# Generated by Django 6.0.5 on 2026-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0004_teacher_password_alter_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='academic_year',
            field=models.CharField(default='2026', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
