# Generated by Django 6.0.5 on 2026-06-03 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0005_schoolclass_academic_year_schoolclass_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_classes', to='main_base.teacher'),
        ),
    ]
