# Generated by Django 6.0.5 on 2026-06-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0006_alter_schoolclass_homeroom_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.CharField(default='Lecture Hall A', max_length=50, verbose_name='上課教室'),
        ),
        migrations.AddField(
            model_name='course',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default='Mon', max_length=3, verbose_name='上課星期'),
        ),
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.CharField(default='09:00 - 12:00', max_length=50, verbose_name='上課時間'),
        ),
    ]
